{% set name = "cfunits-python" %}
{% set version = "1.3.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/48/c2/0765e05f9d8b2d255bb9e1d591cc73d16d23aca402f2757448fc61fb022f/cfunits-1.3.3.tar.gz
  md5: 5abbe561ba9d583500b2f955c3036850A

requirements:
  build:
    - python >=2.7,<3
    - udunits2
    - netcdf4
  run:
    - python
    - udunits2
    - netcdf4

build:
  number: 0
  script: python setup.py install --record record.txt

test:
  imports:
    - cfunits

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT License
  summary: A Python interface to UNIDATA's Udunits-2 package with CF extensions.

