{% set name = "cfunits" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/87/db/fd7412d5ed8b986dcefa30eaf77e05d3b37279c2852269d500583d62a1a3/cfunits-1.5.1.tar.gz
  md5: 544c3d02e3855de30dc56397cc182b54

requirements:
  build:
    - python >=2.7,<3
    - udunits2
    - netcdf4
  run:
    - python
    - udunits2
    - netcdf4

build:
  number: 0
  script: python setup.py install --record record.txt

test:
  imports:
    - cfunits

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT License
  summary:
    "A Python interface to UNIDATA's Udunits-2 package with CF extensions."
