{% set name = "cfunits-python" %}
{% set version = "1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://bitbucket.org/mcflugen/cfunits-python
  git_branch: next

requirements:
  build:
    - python
    - udunits2
    - netcdf4
  run:
    - python
    - udunits2
    - netcdf4

build:
  number: 1
  script: python setup.py install --record record.txt

test:
  imports:
    - cfunits
  source_files:
    - test/
  commands:
    - python test/run_tests.py

about:
  home: https://bitbucket.org/cfpython/cfunits-python
  license: MIT
  license_file: LICENSE
  summary: A python interface to UNIDATA's Udunits-2 package with CF extensions
  dev_url: https://bitbucket.org/cfpython/cfunits-python
