language: generic
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - secure: A05kCsni0KBcVpyrmKGS0ALexEyoLQRRLIk4sAe9Qq0CQaaOew5NGoLNh236l4BjGhO9dXWLISUtaypA6PD0HUIXyK8Z165J6Wpff2Yz1ktqjmXe5zre7hksCBpDNwBmIHn9U4VNXT0EB8ae19wvm1rkTd7t+nmvPB2+LSpwXzHrBOER+tUBQ1iLqu8jkjc8UW0QMf/UAea/YCHMwIxJbDjjeW06Xl/mX1dSLUF83oasn0ALEd366Fd7b5aAQcOevZdw+vlngeBHPdUjsdXsYnLoVOnns1eNRLY0bQrcjz1aSwFGIHUxZNMRH7N1rGFRKtSVHC4tsM0BeVJOSnN2bQ+faH0WNBoP/LxXEcHdSOciK7pCSAsbYA/pUQqMx0MbgowWNbp9lcZqm5uc/GEzdijmcvcohxi9DXsCVyTvRMyQOVtwUzCV5zIwP3kv/tc4N6FzqpvMgDRD+u+SiHAGfy4a7S+pGaWrA6Rk/hzICBxoAue0qRMP1mL6xe9k1NB/33gKp8k5p3ea6lYU0dx7y283wW26HSBSoONuZWUWS2foXZdD7TTi6bs1mdIjj3DJsJ1A7Sb/O+JzMHHq1K885O9TzsANJNdsMXEr8eYN54LjHrwVr/zMvpX0m5gJmzn14CNt32KHBZpU49XfacvUxJGRn4o7hXNn8ZSdVW/15yg=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
- bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
- conda install -q conda-build anaconda-client coverage sphinx
script:
- conda build ./recipe -c csdms-stack -c conda-forge
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms-stack --token=-
